# === Analysis configuration file ======================================================


# --- Configuration for `seqneut-pipeline` ---------------------------------------------

# for this test example the location is "../" but for real analyses it should almost
# certainly be "seqneut-pipeline'
seqneut-pipeline: ../

# for this test example the location is "../docs", but for real analyses it should
# almost certainly be "docs"
docs: ../docs

# change this to a good description of your project
description: |
  # Test example for [seqneut-pipeline](https://github.com/jbloomlab/seqneut-pipeline)
  This is a small toy-example created by subsetting a real experiment dataset.

  See [https://github.com/jbloomlab/seqneut-pipeline](https://github.com/jbloomlab/seqneut-pipeline)
  for the computer code and underlying numerical data.

  See [here](https://github.com/jbloomlab/seqneut-pipeline/graphs/contributors) for a
  list of all contributors to the pipeline.

viral_libraries:
  pdmH1N1_lib2023_loes: data/viral_libraries/pdmH1N1_lib2023_loes.csv

viral_strain_plot_order: data/viral_strain_plot_order.csv

neut_standard_sets:
  loes2023: data/neut_standard_sets/loes2023_neut_standards.csv

illumina_barcode_parser_params:
  upstream: CTCCCTACAATGTCGGATTTGTATTTAATAG
  downstream: ''
  minq: 20
  upstream_mismatch: 4
  bc_orientation: R2

default_process_plate_qc_thresholds: &default_process_plate_qc_thresholds
  avg_barcode_counts_per_well: 250  # 250 for this test, typically >= 500 for real experiments
  min_neut_standard_frac_per_well: 0.005
  no_serum_per_viral_barcode_filters:
    min_frac: 0.0005
    max_fold_change: 3
    max_wells: 2
  per_neut_standard_barcode_filters:
    min_frac: 0.005
    max_fold_change: 3
    max_wells: 2
  min_neut_standard_count_per_well: 500  # 500 for this test, typically >= 1000 for real experiments
  min_no_serum_count_per_viral_barcode_well: 30
  max_frac_infectivity_per_viral_barcode_well: 5
  min_dilutions_per_barcode_serum_replicate: 6

default_process_plate_curvefit_params: &default_process_plate_curvefit_params
  frac_infectivity_ceiling: 1
  fixtop: false
  fixbottom: 0

default_process_plate_curvefit_qc:  &default_process_plate_curvefit_qc
  max_frac_infectivity_at_least: 0.5
  min_R2: 0.8  # you may be able to relax this to more like 0.7 or 0.75
  serum_replicates_ignore_curvefit_qc: []
  barcode_serum_replicates_ignore_curvefit_qc: []

plates:

  plate2:
    date: 2023-08-01
    viral_library: pdmH1N1_lib2023_loes
    neut_standard_set: loes2023
    samples_csv: data/plates/plate2_samples.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc

  plate11:
    date: 2023-09-26
    viral_library: pdmH1N1_lib2023_loes
    neut_standard_set: loes2023
    samples_csv: data/plates/plate11_samples.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
      barcode_serum_replicates_ignore_curvefit_qc:
        - [AGGTCAAGACCACAGG, M099d0]

default_serum_titer_as: midpoint  # can be "midpoint" or "nt50"

default_serum_qc_thresholds:
  min_replicates: 2
  max_fold_change_from_median: 3
  viruses_ignore_qc: []

sera_override_defaults: {}
