#### ================= snakemake configuration file ================= ####

#### ---------------------------- Samples --------------------------- ####

#### -------------------------- Parameters ------------------------- ####

#### -------------------------- Directories ------------------------- ####