#### ================= snakemake configuration file ================= ####

#### ---------------------------- Samples --------------------------- ####

# Contains the fastq file info along with library and neutralization info
barcode_runs: data/barcode_runs.csv

# Contains the barcodes for each strain in a given library 
strain_to_barcode: data/strain_to_barcode.csv

# Contains the barcodes for the neutralization standards for a given set
neut_standards: data/neutralization_standards.csv

# Columns that combine to make a unique identifier for each sample in `barcode_runs`
id_columns: [library, antibody, concentration, replicate, date, plate]

#### -------------------------- Parameters ------------------------- ####

# Parameters for counting Illumina barcodes
illumina_barcode_parser_params:
  upstream: CTCCCTACAATGTCGGATTTGTATTTAATAG
  downstream: ''
  minq: 20
  upstream_mismatch: 4
  downstream_mismatch: 0
  bc_orientation: R2

# Analyze barcodes parameters
analyze_barcodes_params:
  dropdown_columns: ['antibody']

#### -------------------------- Directories ------------------------- ####

# Directory storing csv of barcode counts for each sample
barcode_counts_dir: results/barcode_counts
# Directory for the rendered notebook reports
notebook_dir: results/notebooks
# Directory for storing neutralization assay data
selection_dir: results/selections

####-------------------- Generated Output Files --------------------  ####

# File containing all barcode counts
barcode_counts_file: results/barcode_counts/barcode_counts.csv
# File containing normalized barcode counts
fraction_infectivity_file: results/selections/fraction_infectivity2.csv
# File containing NT50s for each barcode
neutralization_titers_by_barcode: results/selections/nt50_measurements_by_barcode.csv
# File containing NT50s calculated for each strain
neutralization_titers_by_strain: results/selections/nt50_measurements_by_strain.csv