#### ================= snakemake configuration file ================= ####

#### ---------------------------- Samples --------------------------- ####

barcode_runs: barcode_runs.csv
id_columns: ['sample', 'barcode', 'run']


#### -------------------------- Parameters ------------------------- ####

#### -------------------------- Directories ------------------------- ####