name: seqneut-pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.5
  - black
  - mamba
  - marimo=0.16.5
  - markdown=3.9
  - pandas=2.3.3
  - pip
  - pyarrow
  - python=3.13
  - ruamel.yaml=0.18.15
  - snakefmt
  - snakemake=9.13.2
  - ruff
  - pip:
    - dms_variants==1.6.0
    - neutcurve==2.2.0
