name: seqneut-pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.5
  - black-jupyter
  - jupyterlab
  - mamba
  - markdown=3.8
  - pandas=2.3
  - papermill=2.6
  - pip
  - pyarrow
  - python=3.13
  - ruamel.yaml=0.18.14
  - snakefmt
  - snakemake=9.9
  - ruff
  - pip:
    - dms_variants==1.6.0
    - neutcurve==2.2.0
