name: seqneut-pipeline

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - altair=6.2
  - black
  - marimo=0.23  # not used by pipeline, but kept for now in case custom scripts use it
  - markdown=3.10
  - pandas=2.3
  - pillow=12.3
  - pip
  - pyarrow
  - pytest
  - python=3.14
  - ruamel.yaml=0.19
  - snakefmt
  - snakemake=9.25
  - ruff
  - pip:
    - dms_variants==1.6.0
    - neutcurve==2.4.0
